// Shared helpers used by Mongoose models.
// Keep this file dependency-free (no model imports) to avoid circular dependencies.

export const isNonEmptyString = (value: unknown): value is string =>
  typeof value === "string" && value.trim().length > 0;

export const isNonEmptyStringArray = (value: unknown): value is string[] =>
  Array.isArray(value) && value.length > 0 && value.every(isNonEmptyString);

export const isValidEmail = (value: string): boolean => {
  // Intentionally simple; strict RFC email regexes are often counterproductive.
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim());
};

export const slugify = (value: string): string =>
  value
    .trim()
    .toLowerCase()
    .replace(/['"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

// Slugs are generated by `slugify` (lowercase + hyphens).
export const isValidSlug = (slug: string): boolean =>
  /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug);

export const normalizeDateToISO = (value: string): string => {
  // Normalize to `YYYY-MM-DD` (ISO 8601 date) for consistent querying/sorting.
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) throw new Error("Invalid date");
  return d.toISOString().slice(0, 10);
};

export const normalizeTimeToHHmm = (value: string): string => {
  // Accept `H`, `HH`, `H:mm`, `HH:mm`, optionally with `am/pm`, and store as `HH:mm`.
  const match = value
    .trim()
    .match(/^([0-1]?\d|2[0-3])(?::([0-5]\d))?\s*(am|pm)?$/i);
  if (!match) throw new Error("Invalid time");

  let hours = Number(match[1]);
  const minutes = Number(match[2] ?? "0");
  const meridiem = match[3]?.toLowerCase();

  if (meridiem) {
    // Convert 12h clock to 24h.
    if (hours === 12) hours = 0;
    if (meridiem === "pm") hours += 12;
  }

  const hh = String(hours).padStart(2, "0");
  const mm = String(minutes).padStart(2, "0");
  return `${hh}:${mm}`;
};
